# Generated by Django 4.2 on 2023-05-03 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_productimage_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
    ]
